
export const storeProducts = [
  {
    id: 1,
    title: "Google Pixel - Black",
    img: "img/product-1.png",
    price: 10,
    company: "GOOGLE",
    info:
       ["• Model- Google Pixel",
       "• Color- Black",
       "• Camera: AI-powered for stunning photos",
       "• Display: Vibrant AMOLED screen",
       "• Performance: Smooth, powered by strong processor",
       "• OS: Latest Android experience",
       "• Design: Sleek, premium build",
       "• Security: Regular updates, Titan M chip",
       "• Connectivity: Supports 5G",
       "• Battery: All-day life, fast charging"],
    inCart: false,
    count: 0,
    total: 0
  },

  {
    id: 2,
    title: "Samsung S7",
    img: "img/product-2.png",
    price: 16,
    company: "SAMSUNG",
    info:
    ["• Model: Samsung Galaxy S7",
    "• Color: Various options available",
    "• Camera: High-quality, optimized for low light",
    "• Display: Crisp Super AMOLED screen",
    "• Performance: Fast, powered by a robust processor",
    "• OS: Runs on Android with Samsung Experience UI",
    "• Design: Elegant, with a sleek metal construction",
    "• Security: Enhanced with Samsung Knox security platform",
    "• Connectivity: Supports 4G LTE for fast internet access",
    "• Battery: Long-lasting with quick charging capabilities"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "HTC 10 - Black",
    img: "img/product-3.png",
    price: 8,
    company: "htc",
    info:
    ["• Model: HTC 10",
    "• Color: Black",
    "• Camera: UltraPixel technology for improved low-light performance",
    "• Display: Sharp Super LCD 5 screen",
    "• Performance: Responsive, driven by a powerful processor",
    "• OS: Runs on Android with HTC Sense UI",
    "• Design: Premium metal unibody design with chamfered edges",
    "• Security: Enhanced with fingerprint sensor",
    "• Connectivity: Supports 4G LTE for fast data speeds",
    "• Battery: Provides all-day usage with quick charge support"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "HTC 10 - White",
    img: "img/product-4.png",
    price: 18,
    company: "htc",
    info:
    ["• Model: HTC 10",
    "• Color: White",
    "• Camera: Enhanced UltraPixel technology for superior low-light performance",
    "• Display: Crisp Super LCD 5 screen with vivid colors",
    "• Performance: Responsive and efficient, powered by a strong processor",
    "• OS: Runs on Android with HTC Sense UI for a smooth user experience",
    "• Design: Stylish white metal unibody design with chamfered edges",
    "• Security: Enhanced with fingerprint sensor for added protection",
    "• Connectivity: Supports 4G LTE for fast and reliable internet access",
    "• Battery: Long-lasting battery life with quick charge support for convenience"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "HTC Desire 626s",
    img: "img/product-5.png",
    price: 24,
    company: "htc",
    info:
    ["• Model: HTC Desire 626s",
    "• Color: Various color options available",
    "• Camera: Decent camera setup for everyday photography",
    "• Display: Clear and vibrant LCD screen",
    "• Performance: Adequate performance for daily tasks",
    "• OS: Runs on Android with HTC Sense UI for a familiar interface",
    "• Design: Stylish design with a plastic body construction",
    "• Security: Basic security features",
    "• Connectivity: Supports 4G LTE for decent internet speeds",
    "• Battery: Provides moderate battery life for typical usage"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Vintage Iphone",
    img: "img/product-6.png",
    price: 17,
    company: "apple",
    info:
    ["• Model: iPhone 14 Pro",
    "• Color: Various options available",
    "• Camera: Advanced triple-camera system with AI enhancements for exceptional photography",
    "• Display: Stunning Super Retina XDR display with ProMotion technology",
    "• Performance: Powerful A-series chip for seamless multitasking and gaming",
    "• OS: Latest iOS version with exclusive Pro features",
    "• Design: Premium design with durable materials and sleek finish",
    "• Security: Advanced Face ID for secure authentication",
    "• Connectivity: Supports 5G for lightning-fast internet speeds",
    "• Battery: Long-lasting battery life with fast charging capabilities"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Iphone 7",
    img: "img/product-7.png",
    price: 30,
    company: "apple",
    info:
    ["• Model: iPhone 7",
    "• Color: Various options available",
    "• Camera: Improved camera system with optical image stabilization",
    "• Display: Retina HD display with wide color gamut",
    "• Performance: Smooth performance powered by Apple A10 Fusion chip",
    "• OS: Runs on iOS with regular updates",
    "• Design: Sleek aluminum design with water and dust resistance",
    "• Security: Enhanced security features with Touch ID fingerprint sensor",
    "• Connectivity: Supports 4G LTE for fast data speeds",
    "• Battery: Provides all-day battery life with efficient power management"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Smashed Iphone",
    img: "img/product-8.png",
    price: 2,
    company: "apple",
    info:
["• Model: iPhone X",
"• Color: Various",
"• Camera: Dual-camera system",
"• Display: Super Retina OLED",
"• Performance: A11 Bionic chip",
"• OS: Latest iOS version",
"• Design: Premium glass and steel",
"• Security: Face ID",
"• Connectivity: 4G LTE",
"• Battery: All-day life, wireless charging"],
    inCart: false,
    count: 0,
    total: 0
  }
];





export const detailProduct = [
  {
    id: 1,
    title: "Google Pixel - Black",
    img: "img/product-1.png",
    price: 10,
    company: "GOOGLE",
    info:
       ["• Model- Google Pixel",
       "• Color- Black",
       "• Camera: AI-powered for stunning photos",
       "• Display: Vibrant AMOLED screen",
       "• Performance: Smooth, powered by strong processor",
       "• OS: Latest Android experience",
       "• Design: Sleek, premium build",
       "• Security: Regular updates, Titan M chip",
       "• Connectivity: Supports 5G",
       "• Battery: All-day life, fast charging"],
    inCart: false,
    count: 0,
    total: 0
  },

  {
    id: 2,
    title: "Samsung S7",
    img: "img/product-2.png",
    price: 16,
    company: "SAMSUNG",
    info:
    ["• Model: Samsung Galaxy S7",
    "• Color: Various options available",
    "• Camera: High-quality, optimized for low light",
    "• Display: Crisp Super AMOLED screen",
    "• Performance: Fast, powered by a robust processor",
    "• OS: Runs on Android with Samsung Experience UI",
    "• Design: Elegant, with a sleek metal and construction",
    "• Security: Enhanced with Samsung Knox security platform",
    "• Connectivity: Supports 4G LTE for fast internet access",
    "• Battery: Long-lasting with quick charging capabilities"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "HTC 10 - Black",
    img: "img/product-3.png",
    price: 8,
    company: "htc",
    info:
    ["• Model: HTC 10",
    "• Color: Black",
    "• Camera: UltraPixel technology for improved low-light performance",
    "• Display: Sharp Super LCD 5 screen",
    "• Performance: Responsive, driven by a powerful processor",
    "• OS: Runs on Android with HTC Sense UI",
    "• Design: Premium metal unibody design with chamfered edges",
    "• Security: Enhanced with fingerprint sensor",
    "• Connectivity: Supports 4G LTE for fast data speeds",
    "• Battery: Provides all-day usage with quick charge support"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "HTC 10 - White",
    img: "img/product-4.png",
    price: 18,
    company: "htc",
    info:
    ["• Model: HTC 10",
    "• Color: White",
    "• Camera: Enhanced UltraPixel technology for superior low-light performance",
    "• Display: Crisp Super LCD 5 screen with vivid colors",
    "• Performance: Responsive and efficient, powered by a strong processor",
    "• OS: Runs on Android with HTC Sense UI for a smooth user experience",
    "• Design: Stylish white metal unibody design with chamfered edges",
    "• Security: Enhanced with fingerprint sensor for added protection",
    "• Connectivity: Supports 4G LTE for fast and reliable internet access",
    "• Battery: Long-lasting battery life with quick charge support for convenience"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "HTC Desire 626s",
    img: "img/product-5.png",
    price: 24,
    company: ["• Model: HTC Desire 626s",
    "• Color: Various color options available",
    "• Camera: Decent camera setup for everyday photography",
    "• Display: Clear and vibrant LCD screen",
    "• Performance: Adequate performance for daily tasks",
    "• OS: Runs on Android with HTC Sense UI for a familiar interface",
    "• Design: Stylish design with a plastic body construction",
    "• Security: Basic security features",
    "• Connectivity: Supports 4G LTE for decent internet speeds",
    "• Battery: Provides moderate battery life for typical usage"],
    info:
      "Lorem ipsum",
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Vintage Iphone",
    img: "img/product-6.png",
    price: 17,
    company: "apple",
    info:
    ["• Model: iPhone 14 Pro",
    "• Color: Various options available",
    "• Camera: Advanced triple-camera system with AI enhancements for exceptional photography",
    "• Display: Stunning Super Retina XDR display with ProMotion technology",
    "• Performance: Powerful A-series chip for seamless multitasking and gaming",
    "• OS: Latest iOS version with exclusive Pro features",
    "• Design: Premium design with durable materials and sleek finish",
    "• Security: Advanced Face ID for secure authentication",
    "• Connectivity: Supports 5G for lightning-fast internet speeds",
    "• Battery: Long-lasting battery life with fast charging capabilities"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Iphone 7",
    img: "img/product-7.png",
    price: 30,
    company: "apple",
    info:
    ["• Model: iPhone 7",
    "• Color: Various options available",
    "• Camera: Improved camera system with optical image stabilization",
    "• Display: Retina HD display with wide color gamut",
    "• Performance: Smooth performance powered by Apple A10 Fusion chip",
    "• OS: Runs on iOS with regular updates",
    "• Design: Sleek aluminum design with water and dust resistance",
    "• Security: Enhanced security features with Touch ID fingerprint sensor",
    "• Connectivity: Supports 4G LTE for fast data speeds",
    "• Battery: Provides all-day battery life with efficient power management"],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Smashed Iphone",
    img: "img/product-8.png",
    price: 2,
    company: "apple",
    info:
["• Model: iPhone X",
"• Color: Various",
"• Camera: Dual-camera system",
"• Display: Super Retina OLED",
"• Performance: A11 Bionic chip",
"• OS: Latest iOS version",
"• Design: Premium glass and steel",
"• Security: Face ID",
"• Connectivity: 4G LTE",
"• Battery: All-day life, wireless charging"],
    inCart: false,
    count: 0,
    total: 0
  }
];